import type { Metadata } from 'next';
import '@/styles/globals.css';
import { AppLayout } from '@/components/layouts';

export const metadata: Metadata = {
  title: 'Bruce | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
