name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --force

      - name: Build the app
        run: CI=false npm run build

      - name: Copy build directory to temporary location
        run: |
          mkdir ../build-temp
          cp -r build/* ../build-temp/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy build contents to gh-pages
        run: |
          cp -r ../build-temp/* gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "Bruce-zzhu"
          git config user.email "brucezzhu@gmail.com"
          git add .
          git commit -m "cd: deploy to gh-pages"
          git push origin gh-pages
